import styles from '../styles/Home.module.css'
import ThemeToggle from './elements/ToggleTheme/ToggleTheme'
import SidebarItem from './elements/SidebarItem/SidebarItem'
import Head from 'next/head'
import { useState, useEffect } from 'react' 

export default function IndexLayout({children}){

  const darkTheme = () => {
    if(localStorage.getItem('color-theme') === 'dark' || (!('color-theme' in localStorage) && window.matchMedia('(prefers-color-scheme: dark)').matches)) {
      document.documentElement.classList.add('dark');
    } 
    else {
      document.documentElement.classList.remove('dark')
    }
  }

  useEffect(() => {
    darkTheme()
  },[])

  return(
    <div>
      <Head>
        <title>GRASSR00T | Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="
        flex 
        flex-colum 
        justify-center 
        align-center
        dark:bg-black
        h-[100vh]
        ">
        <div className="
          flex 
          flex-column 
          h-[100vh] 
          dark:bg-[url('https://f4-public.s3.eu-central-1.amazonaws.com/imageedit_3_8959513005.png')]
          bg-[url('https://f4-public.s3.eu-central-1.amazonaws.com/imageedit_19_3200557394.png')]
          ">
          <div className="grid place-items-center">
            {children}
          </div>
        </div>
      </main>
    </div>
  )
}
