apiVersion: v1
kind: Service
metadata:
  name: f4-frontend-lb
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:eu-central-1:236798077409:certificate/de9f25c8-6dc8-492e-9382-e849bec81cf5
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
spec:
  type: LoadBalancer
  selector:
    app: frontend
  ports:
    - name: https
      port: 443
      targetPort: 3000
    - name: http
      port: 80
      targetPort: 3000
